insert into product_dim (product_id, productname) values (1, 'Flour - Buckwheat, Dark');
insert into product_dim (product_id, productname) values (2, 'Champagne - Brights, Dry');
insert into product_dim (product_id, productname) values (3, 'Buffalo - Striploin');
insert into product_dim (product_id, productname) values (4, 'Pasta - Penne, Lisce, Dry');
insert into product_dim (product_id, productname) values (5, 'Icecream - Dibs');
insert into product_dim (product_id, productname) values (6, 'Sauce - Thousand Island');
insert into product_dim (product_id, productname) values (7, 'Snapple Raspberry Tea');
insert into product_dim (product_id, productname) values (8, 'Beef - Bresaola');
insert into product_dim (product_id, productname) values (9, 'Paper Towel Touchless');
insert into product_dim (product_id, productname) values (10, 'Transfer Sheets');
insert into product_dim (product_id, productname) values (11, 'Cheese - Cheddar With Claret');
insert into product_dim (product_id, productname) values (12, 'Table Cloth 62x120 Colour');
insert into product_dim (product_id, productname) values (13, 'Wine - Rubyport');
insert into product_dim (product_id, productname) values (14, 'Watercress');
insert into product_dim (product_id, productname) values (15, 'Appetizer - Assorted Box');
insert into product_dim (product_id, productname) values (16, 'Leeks - Baby, White');
insert into product_dim (product_id, productname) values (17, 'Bread - Raisin Walnut Pull');
insert into product_dim (product_id, productname) values (18, 'Kellogs Raisan Bran Bars');
insert into product_dim (product_id, productname) values (19, 'Crawfish');
insert into product_dim (product_id, productname) values (20, 'Oil - Truffle, White');
insert into product_dim (product_id, productname) values (21, 'Cheese Cloth No 60');
insert into product_dim (product_id, productname) values (22, 'Cod - Black Whole Fillet');
insert into product_dim (product_id, productname) values (23, 'Syrup - Monin, Amaretta');
insert into product_dim (product_id, productname) values (24, 'Beef Wellington');
insert into product_dim (product_id, productname) values (25, 'Wine - Mas Chicet Rose, Vintage');

insert into country_dim (country_id, countryname) values (1, 'China');
insert into country_dim (country_id, countryname) values (2, 'Indonesia');
insert into country_dim (country_id, countryname) values (3, 'Hungary');
insert into country_dim (country_id, countryname) values (4, 'Guatemala');
insert into country_dim (country_id, countryname) values (5, 'Nepal');
insert into country_dim (country_id, countryname) values (6, 'Afghanistan');
insert into country_dim (country_id, countryname) values (7, 'Indonesia');
insert into country_dim (country_id, countryname) values (8, 'Portugal');
insert into country_dim (country_id, countryname) values (9, 'China');
insert into country_dim (country_id, countryname) values (10, 'Cyprus');

insert into date_dim (date_id, date) values (1, '4/24/2021');
insert into date_dim (date_id, date) values (2, '7/7/2021');
insert into date_dim (date_id, date) values (3, '10/6/2021');
insert into date_dim (date_id, date) values (4, '5/12/2021');
insert into date_dim (date_id, date) values (5, '9/14/2021');
insert into date_dim (date_id, date) values (6, '2/6/2021');
insert into date_dim (date_id, date) values (7, '6/7/2021');
insert into date_dim (date_id, date) values (8, '12/7/2020');
insert into date_dim (date_id, date) values (9, '5/30/2021');
insert into date_dim (date_id, date) values (10, '3/2/2021');
insert into date_dim (date_id, date) values (11, '4/4/2021');
insert into date_dim (date_id, date) values (12, '9/13/2021');
insert into date_dim (date_id, date) values (13, '10/2/2021');
insert into date_dim (date_id, date) values (14, '5/8/2021');
insert into date_dim (date_id, date) values (15, '10/14/2020');

insert into city_dim (city_id, city) values (1, 'La Rochelle');
insert into city_dim (city_id, city) values (2, 'Jianping');
insert into city_dim (city_id, city) values (3, 'Budapest');
insert into city_dim (city_id, city) values (4, 'Kangasala');
insert into city_dim (city_id, city) values (5, 'Simpang');
insert into city_dim (city_id, city) values (6, 'Barat');
insert into city_dim (city_id, city) values (7, 'Fantan');
insert into city_dim (city_id, city) values (8, 'Carapelhos');
insert into city_dim (city_id, city) values (9, 'Lubāna');
insert into city_dim (city_id, city) values (10, 'Thị Trấn Tà Lùng');
insert into city_dim (city_id, city) values (11, 'Qianxu Zhen');
insert into city_dim (city_id, city) values (12, 'Juuka');
insert into city_dim (city_id, city) values (13, 'Osapsio');
insert into city_dim (city_id, city) values (14, 'Vilar');
insert into city_dim (city_id, city) values (15, 'Skuodas');
insert into city_dim (city_id, city) values (16, 'Soito');
insert into city_dim (city_id, city) values (17, 'Calimita');
insert into city_dim (city_id, city) values (18, 'Longfeng');
insert into city_dim (city_id, city) values (19, 'Fengyang');
insert into city_dim (city_id, city) values (20, 'Angeghakot’');

insert into customer_dim (customer_id) values (1);
insert into customer_dim (customer_id) values (2);
insert into customer_dim (customer_id) values (3);
insert into customer_dim (customer_id) values (4);
insert into customer_dim (customer_id) values (5);
insert into customer_dim (customer_id) values (6);
insert into customer_dim (customer_id) values (7);
insert into customer_dim (customer_id) values (8);
insert into customer_dim (customer_id) values (9);
insert into customer_dim (customer_id) values (10);
insert into customer_dim (customer_id) values (11);
insert into customer_dim (customer_id) values (12);
insert into customer_dim (customer_id) values (13);

insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (1, 5, 6, 12, 18, 12, 6, 889);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (2, 19, 4, 10, 8, 13, 10, 177);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (3, 15, 1, 9, 14, 2, 21, 96);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (4, 4, 7, 14, 17, 4, 11, 1684);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (5, 17, 7, 6, 4, 9, 7, 800);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (6, 3, 3, 5, 13, 5, 32, 1873);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (7, 5, 4, 1, 12, 6, 20, 758);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (8, 22, 8, 12, 1, 1, 7, 194);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (9, 3, 10, 9, 16, 8, 32, 1691);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (10, 10, 2, 2, 7, 3, 15, 98);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (11, 17, 1, 10, 20, 11, 8, 1900);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (12, 3, 3, 11, 10, 1, 9, 1039);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (13, 19, 10, 8, 5, 6, 7, 1080);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (14, 13, 8, 10, 15, 8, 7, 1811);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (15, 4, 10, 11, 10, 7, 15, 765);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (16, 2, 6, 3, 5, 5, 24, 624);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (17, 17, 7, 11, 17, 12, 30, 1573);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (18, 8, 6, 13, 5, 8, 12, 1931);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (19, 24, 7, 8, 19, 11, 13, 1290);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (20, 5, 3, 12, 9, 2, 9, 546);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (21, 11, 5, 14, 4, 2, 33, 1848);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (22, 4, 6, 1, 13, 3, 6, 429);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (23, 21, 3, 15, 6, 4, 32, 1166);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (24, 24, 3, 14, 14, 6, 28, 1112);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (25, 4, 1, 1, 17, 8, 2, 422);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (26, 10, 7, 6, 8, 13, 8, 462);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (27, 4, 5, 11, 6, 8, 23, 750);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (28, 20, 7, 6, 10, 4, 18, 962);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (29, 2, 10, 2, 8, 6, 9, 743);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (30, 7, 1, 9, 10, 5, 16, 1922);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (31, 8, 5, 14, 20, 9, 7, 1980);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (32, 13, 4, 1, 15, 10, 27, 92);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (33, 19, 1, 12, 19, 9, 32, 1823);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (34, 6, 4, 6, 7, 6, 11, 750);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (35, 15, 2, 6, 11, 8, 3, 1096);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (36, 1, 5, 11, 5, 10, 19, 640);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (37, 20, 9, 10, 10, 11, 2, 48);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (38, 17, 7, 1, 19, 3, 17, 1020);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (39, 17, 10, 7, 15, 13, 4, 1118);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (40, 23, 10, 7, 16, 11, 10, 884);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (41, 18, 1, 15, 20, 3, 11, 77);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (42, 24, 10, 12, 10, 3, 13, 1880);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (43, 8, 4, 15, 17, 4, 20, 943);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (44, 15, 1, 4, 20, 4, 25, 1040);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (45, 10, 4, 10, 7, 6, 4, 1315);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (46, 5, 9, 3, 5, 5, 19, 951);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (47, 10, 8, 8, 15, 13, 10, 1760);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (48, 4, 9, 7, 18, 10, 7, 1576);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (49, 18, 7, 15, 11, 10, 27, 863);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (50, 8, 1, 3, 3, 11, 25, 1077);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (51, 4, 3, 8, 16, 3, 18, 1669);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (52, 7, 6, 11, 10, 6, 28, 196);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (53, 1, 4, 7, 20, 6, 21, 522);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (54, 3, 8, 7, 6, 5, 33, 1341);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (55, 13, 10, 6, 5, 9, 10, 1527);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (56, 20, 2, 5, 10, 7, 27, 1837);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (57, 18, 8, 12, 5, 10, 8, 1900);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (58, 4, 7, 11, 18, 6, 25, 1100);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (59, 2, 3, 6, 18, 4, 2, 1624);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (60, 18, 5, 3, 20, 10, 9, 639);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (61, 16, 10, 1, 6, 5, 19, 1798);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (62, 11, 1, 4, 5, 11, 12, 1559);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (63, 19, 7, 12, 7, 4, 23, 80);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (64, 1, 2, 13, 12, 12, 24, 1493);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (65, 22, 8, 9, 5, 3, 23, 1569);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (66, 12, 2, 9, 9, 13, 8, 870);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (67, 22, 9, 8, 18, 2, 9, 1108);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (68, 12, 3, 13, 6, 12, 30, 914);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (69, 25, 4, 5, 14, 3, 14, 1432);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (70, 12, 8, 2, 18, 1, 21, 1208);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (71, 1, 9, 1, 4, 2, 15, 1580);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (72, 11, 4, 10, 14, 7, 27, 832);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (73, 7, 5, 13, 2, 4, 12, 220);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (74, 20, 4, 11, 18, 11, 12, 1908);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (75, 1, 1, 8, 20, 8, 12, 552);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (76, 10, 8, 14, 18, 10, 15, 958);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (77, 11, 9, 6, 19, 8, 6, 241);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (78, 3, 7, 4, 2, 4, 27, 91);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (79, 24, 5, 14, 5, 6, 17, 965);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (80, 18, 9, 15, 15, 2, 14, 775);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (81, 11, 9, 9, 5, 3, 26, 1109);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (82, 24, 5, 15, 6, 10, 24, 309);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (83, 9, 3, 12, 14, 13, 10, 1218);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (84, 1, 10, 6, 6, 13, 22, 1571);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (85, 13, 3, 1, 3, 6, 11, 723);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (86, 10, 2, 1, 5, 8, 19, 745);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (87, 10, 2, 5, 8, 9, 31, 135);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (88, 5, 2, 2, 4, 3, 22, 1892);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (89, 22, 8, 5, 2, 5, 6, 1176);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (90, 10, 9, 1, 6, 8, 11, 869);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (91, 8, 3, 14, 10, 7, 5, 1226);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (92, 17, 8, 13, 10, 13, 27, 668);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (93, 6, 8, 8, 8, 11, 23, 545);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (94, 11, 2, 5, 3, 10, 14, 35);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (95, 6, 9, 9, 10, 2, 31, 166);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (96, 15, 10, 14, 8, 7, 4, 1748);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (97, 21, 6, 12, 15, 3, 23, 212);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (98, 2, 10, 4, 14, 12, 4, 345);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (99, 20, 8, 6, 18, 9, 15, 1861);
insert into customer_dim (sales_id, product_id, country_id, date_id, city_id, customer_id, quantity, sales) values (100, 25, 4, 11, 15, 5, 22, 1044);